import Head from 'next/head'
import { useEffect, useState } from 'react'
import Auth from '../components/Auth'
import { supabase } from '../utils/supabaseClient'
import PrivateArea from '../components/PrivateArea'


export default function Home() {
  const [ UserSession , setUserSession] = useState(null)


  useEffect(() => {
    (async()=>{
      setUserSession(supabase.auth.getSession())
      supabase.auth.onAuthStateChange((event, session) => {
      setUserSession(session)

     
      })
    })()
  }, [])
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container d-flex justify-content-center'>
      {
        UserSession !== null ? <PrivateArea/>: <Auth />
      }
      </main>

 
    </div>
  )
}
